- name: Test librenms get
  hosts: localhost
  vars_files:
    - vars/libre.yml
  tasks:
   - name: Get a specific device.
     libre_devices_info:
      api_url: {{ api_url }}
      api_token: {{ api_token }}
      query_params:
       - type: down
     register: testout
   - name: Dump output
     ansible.builtin.debug:
      msg: '{{ testout }}'
