- name: Test librenms get
  hosts: localhost
  vars_files:
    - vars/libre.yml
  tasks:
   - name: Get a specific device.
     libre_devices_info:
      api_url: {{ api_url }}
      api_token: {{ api_token }}
      name: 1.1.1.1
     register: device_info
   - name: Print output
     ansible.builtin.debug:
      var: device_info.data
